question_data = [
     {"category": "Science & Nature",
      "type": "boolean",
      "difficulty": "medium",
      "question": "The Doppler effect applies to light.",
      "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
      "question": "Hippopotomonstrosesquippedaliophobia is the irrational fear of long words.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
      "question": "The &quot;Gympie Stinger&quot; is the deadliest plant in the world.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
      "question": "Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
      "question": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
      "question": "Scientists accidentally killed the once known world&#039;s oldest living creature, a mollusc, known to be aged as 507 years old.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
      "question": "In the periodic table, Potassium&#039;s symbol is the letter K.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
      "question": "Sugar contains fat.", "correct_answer": "False",
      "incorrect_answers": ["True"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
      "question": "The most frequent subconscious activity repeated by the human body is blinking.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
      "question": "&quot;Tachycardia&quot; or &quot;Tachyarrhythmia&quot; refers to a resting heart-rate near or over 100 BPM.",
      "correct_answer": "True", "incorrect_answers": ["False"]}
]
